import LayoutRoot from '@/Layouts/LayoutRoot';

export default function WelcomeRoot() {

    const handleVisible = () => {
        //ocultar o hacer visible el contenedor
        var element = document.getElementById('contenedorVisibilidad');
        element.className = element.className === "oculto" ? "visible" : "oculto";

        //cambiar el texto del botón de ver más
        var boton = document.getElementById('botonVisibilidad');
        boton.innerHTML = boton.innerHTML === "Leer más" ? "Leer menos" : "Leer más";
    };

    return (
        <>
            <LayoutRoot>
                <main className=" bg-main h-auto py-10 px-4">
                    <p className="my-2"><b>Walter Bruce Willis</b> (Idar-Oberstein, Alemania Occidental; 19 de marzo de 1955) es un actor retirado, productor y músico estadounidense, cuya trayectoria comenzó en la industria televisiva durante los años 1980. Ha interpretado roles cómicos, dramáticos y de acción. Es conocido por su interpretación del oficial John McClane en la saga La jungla de cristal, que obtuvo buenas críticas y una recaudación considerable a partir del estreno de la primera cinta en 1988.​ Asimismo, ha aparecido en más de sesenta películas, entre las que se incluyen éxitos de taquilla como Pulp Fiction, Sin City, Doce monos, El quinto elemento, Armageddon, El sexto sentido, El protegido, Glass, Looper, Lucky Number Slevin o The Expendables.
                    </p>
                    <p className="my-2">Las películas en las que ha aparecido Willis han logrado sumar 7500 millones de dólares en las taquillas de todo el mundo, por lo que se le considera como uno de los actores más rentables en un rol estelar o secundario. ​Por sus interpretaciones, ha sido acreedor de varios premios, entre ellos dos premios Emmy, un Globo de Oro y cuatro Saturn.</p>
                    <p className="my-2">En cuanto a su vida privada, se casó con la actriz Demi Moore, con quien tuvo tres hijas antes de su divorcio en 2000, después de trece años de matrimonio. Tiempo después contrajo matrimonio con la modelo Emma Heming.​</p>
                    <p className="my-2">En marzo de 2022 su familia anunció que se retiraría de la actuación tras haber sido diagnosticado con afasia, un trastorno de lenguaje que afecta a la capacidad de comunicación de una persona.​ Sin embargo, en febrero de 2023 informaron que su condición médica había avanzado y que disponían de un diagnóstico más específico: demencia frontotemporal, conocida como FTD.</p>
                    <h2 className="mw-headline text-2xl py-10 text-center"><b>Biografía</b></h2>
                    <h3 className=" mb-5 text-xl"><b>Primeros años</b></h3>
                    <p className="my-2">Willis nació en Idar-Oberstein, Alemania Occidental, hijo de Marlene, una alemana nacida en Kassel y que trabajaba en un banco, y David Willis, un soldado estadounidense. Es el mayor de cuatro hermanos: Florence, David y Robert —este último murió de cáncer de páncreas en 2001, a la edad de 42 años—.​ Su familia paterna es de ascendencia mayoritariamente inglesa y en menor medida neerlandesa, francesa, galesa e irlandesa.​ Tras abandonar el ejército en 1957, el padre de Willis llevó a su familia de una base militar alemana donde radicaban al asentamiento Carneys Point, Nueva Jersey, donde consiguió empleos como soldador y trabajador en una fábrica. Para entonces, Bruce Willis contaba apenas dos años de edad.​ Tiempo después, en 1972, período en que Willis era un adolescente y vivía en Penns Grove, Nueva Jersey, sus padres se divorciaron.​ En esas mismas fechas, inició sus estudios de secundaria en Penns Grove High School, donde padeció problemas de tartamudez y recibió por parte de sus compañeros de clase el apodo <i>Buck-Buck</i> debido a ello.​​ El escritor británico John Parker, en su libro <i>Bruce Willis: The Unauthorized Biography</i> (1997), menciona que Willis recurrió, aconsejado por su profesor de teatro en la escuela Jerry Rockwood,​ a una especie de «ejercicios» para fortalecer su confianza, impartidos por un especialista escolar en el habla, y fue así como perdió su tartamudez. Según el propio Willis (tal y como aparece citado en la obra mencionada): «Casi no podía hablar. Me tomaba tres minutos completar una sola oración. Era algo abrumador para alguien que quería expresarse ante los demás y que quería ser escuchado pero que simplemente no podía. Era espantoso. No fue sino cuando asumí el rol de un personaje, en una obra de teatro, cuando perdí el balbuceo. Fue fenomenal».</p>
                    <img className="max-h-full float-right m-3" src="/images/nuevaJersey.jpg" alt="Nueva Jersey" title="Nueva Jersey" />
                    <p className="my-2">Sobre este difícil aspecto de su vida, el libro <i>Bruce Willis: Overcoming Adversity</i> (2001), escrito por Sandy Asirvatham, hace mención de que Willis se mostraba a veces renuente a dialogar sobre su infancia en algunas entrevistas, puesto que dicha etapa había sido dolorosa para él.​ Parker detalla en su libro que, para Willis, una solución primeriza para lidiar con su balbuceo fue convertirse en el joven bromista de su escuela; en esta misma obra, un profesor de la secundaria Penns Grove añade que «para cuando la mayoría de los chicos estaba encontrando su identidad, Willis pasaba por un período difícil. El balbuceo era un problema así que, al final, decidió compensarlo haciéndole travesuras a los demás».​ Tras superar su problema de tartamudez, comenzó a aparecer en pequeños roles hasta convertirse en el presidente del club de teatro y del consejo estudiantil, en 1971.​ Si bien Willis recurrió a las obras escolares para superar su problema de tartamudez, no consideraba aún convertirse en un actor. En 1972 se inscribió en las clases de lucha de su escuela, en donde poco después se habría de desgarrar el hombro y, a raíz de ello, le quedaría una cicatriz.​ Tan solo un año después, a sus 18 años de edad, fue suspendido por un período de tres meses de la Penns Grove High School, tras involucrarse en lo que conocían entre la comunidad estudiantil como «el motín anual».</p>
                    <p className="my-2">Una vez que se graduó de la Penns Grove High School, en 1973, Willis consiguió un empleo en la fábrica DuPont Chambers Works, ubicada en Deepwater, Nueva Jersey.​ No obstante, renunció después de que uno de sus colegas murió en el área de trabajo, y visitó con cierta regularidad bares de la región a partir de dicho suceso, donde empezó también a tocar la armónica junto con una banda de R&amp;B denominada Loose Goose.​ Meses después fue contratado como vigilante de seguridad en la planta de energía nuclear Salem, la cual se hallaba en plena construcción para entonces.</p>
                    <p className="my-2">Regresó a la actuación tras desempeñarse brevemente como investigador privado,​ papel que habría de interpretar en la serie de televisión <i>Luz de luna</i> y en la cinta <i>El último boy scout</i> (1991). Cursó sus estudios universitarios en la Universidad de Montclair al afiliarse a un programa de drama y comenzó a interesarse un poco más en la actuación.​ Ahí, resultó elegido en la producción de <i>La gata sobre el tejado de zinc</i>, donde elogiaron su interpretación.​ Incluso se tiene conocimiento de que Willis estudió con la conocida profesora Stella Adler.​ Tres años después, en 1977, decidió dejar sus estudios universitarios para mudarse a la ciudad de Nueva York —donde consiguió un departamento que compartió con la actriz Linda Fiorentino—​ y poco después establecerse en el barrio Hell's Kitchen de Manhattan, Nueva York.​ Respecto a lo anterior, el actor comentó: «Un certificado escolar es sólo un trofeo. Tengo algunos trofeos de bolos que creo que son igual de valiosos que los diplomas».</p>
                    <p className="my-2">Para subsistir económicamente, el actor volvió a buscar empleo en bares y restaurantes, esta vez para obtener un trabajo a tiempo parcial en el West Bank Café, ubicado en el complejo Manhattan Plaza.​ Tras numerosas audiciones, en 1977 hizo su debut teatral en la producción <i>off-Broadway</i> (es decir, una obra llevada a cabo en Nueva York, pero independiente del concepto de Broadway) de <i>Heaven and Earth</i>.​ Después apareció en la obra <i>Fool for Love</i>, escrita por el guionista Sam Shepard, donde participó en más de un centenar de obras teatrales,​ así como en uno de los primeros anuncios comerciales de la empresa Levi's para promocionar su modelo 501 Blues de <i>jeans</i>.</p>
                    <h3 className=" mb-5 text-xl mt-5"><b>Carrera</b></h3>
                    <h4 className="mb-5 text-xl mt-3"><b>1980-1990</b></h4>
                    <p className="my-2">En 1980 ocurrió su debut en el cine al participar como un extra en la producción <i>El primer pecado mortal</i>, protagonizada por Frank Sinatra.​ Tiempo después, dejó la ciudad de Nueva York para irse a California, donde participó en audiciones para programas televisivos.​ En noviembre de 1984, apareció en un episodio de la serie <i>Miami Vice</i> titulado «No Exit», perteneciente a la primera temporada, donde interpretó a Tony Amato, un traficante de armas.​ Asimismo, coincidentemente al hacer un viaje a Los Ángeles para participar en la película <i>Desperately Seeking Susan</i>, protagonizada por Madonna (si bien al final no resultó elegido),​ se involucró en el <i>casting</i> para el papel de David Addison Jr, uno de los personajes de <i>Luz de luna</i> (1985-1989), donde compitió contra un total de 3.000 actores que querían ese mismo papel.​  <img className="max-h-full float-right m-3" src="/images/willis_80.jpg" alt="willis" title="willis y Cybill Lynne Shepherd" />Dicho papel lo ayudó a consolidarse como un actor de comedia y el programa llegó a un total de cinco temporadas. Debido al éxito del mismo, la compañía fabricante de bebidas alcohólicas Seagram contrató a Willis, junto con Sharon Stone, para promocionar en televisión sus productos Golden Wine Cooler.​ Aunque su nuevo empleo en dicha campaña publicitaria le valió un salario de entre 5 y 7 millones de dolares por los próximos dos años, determinó no renovar su contrato por un tercer año, puesto que había dejado de beber en 1988.​ En 1985, actuó en el episodio «Shatterday», el primero de la nueva versión <i>The Twilight Zone</i> de la serie homónima de la década de 1950.​ Dos años después, en el fin de semana del día de los caídos de 1987, fue arrestado tras perturbar la paz y agredir a un oficial; no obstante, los cargos fueron retirados una vez que este se disculpó con el policía.​ Algunas fuentes mencionan que esta fue la verdadera causa por la que Seagram lo despidió.</p>
                    <p className="my-2">Uno de sus primeros papeles estelares notables fue en la película <i>Cita a ciegas</i> (1987), dirigida por Blake Edwards y protagonizada también por los actores Kim Basinger y John Larroquette. Tras su estreno, el filme recaudó un total de 39&nbsp;321&nbsp;715 dolares en territorio estadounidense,​ y de acuerdo a <i>Variety</i>: «[En <i>Cita a ciegas</i>], Bruce Willis abandona su personalidad televisiva de asaltante con tal de personificar a un analista financiero divertido, amable, trabajador y ambicioso en Los Ángeles. El concepto del caos natural se desarrolla bien debido a la química en el trío principal de actores, Willis, Basinger y Larroquette».​ Edwards lo volvió a contratar para una producción suya, <i>Asesinato en Beverly Hills</i> (1988), donde Willis interpreta al vaquero y actor Tom Mix. La película tuvo un resultado rotundamente negativo en taquilla, al recaudar únicamente 4,5 millones de dolares, si se considera que el presupuesto estimado para producirla fue de 16 millones de dolares.​ Del mismo modo, obtuvo malas críticas a nivel general; por ejemplo, Vicent Canby, de <i>New York Times</i>, mencionó: «Es una historia que se descifra por sí sola, sin personajes, sin nada, ni siquiera con un punto de vista. Es un zombi».​ No fue sino hasta su incorporación en la cinta <i>Die Hard</i> (1988) que Willis fue catapultado a la fama. Resulta destacable mencionar que él realizó sus propias escenas de riesgo en la película,​ la cual, tras su estreno, recaudó un total de 138&nbsp;708&nbsp;852 dolares a nivel mundial,​ además de obtener excelentes críticas, que la catalogaron instantáneamente como una de las mejores películas de acción del cine contemporáneo. Lo anterior puede evidenciarse en el sitio web Rotten Tomatoes, donde el 94% de las críticas son positivas, con lo que logra un promedio de 8,2/10 a nivel general.</p>
                    <p className="my-2">Tras el éxito de <i>Die Hard</i>, obtuvo un papel secundario en el drama <i>In Country</i>, que se estrenó en septiembre de 1989, en la que interpretó al veterano de la guerra de Vietnam Emmett Smith. Dicha película se estrenó a nivel mundial en el Festival de cine de Toronto,​ al cual Willis asistió y donde dedicó inclusive el debut de la misma a todos los veteranos canadienses de guerra que pelearon en Vietnam. La película recaudó un total de 3&nbsp;531&nbsp;971 en Estados Unidos​ y obtuvo buenas críticas tras su estreno, además de conseguir un <i>rating</i> de 82% en Rotten Tomatoes; Roger Ebert mencionó en su crítica: «La película es como una bomba de tiempo. Te sientas ahí, interesado, absorto, a veces entretenido, en otras emocionado, pero piensas en el fondo de tu mente sobre dónde irá a terminar la historia. Entonces, es cuando lo descubres».​ A su vez, <i>USA Today</i> elogió el trabajo de Willis y comentó que su «actuación secundaria como el tío guardián solitario de Emily Lloyd es admirablemente escasa en exhibicionismo».​ Poco después prestó su voz para el bebé parlante de la película <i>Mira quién habla</i> (1989), la cual obtuvo ganancias estimadas en 296&nbsp;999&nbsp;813 dolares a nivel mundial;​ en su crítica, Chris Willman, de <i>Los Angeles Times</i>, subrayó: «Filmes donde los animales, bebés o demás seres sin voz pueden decir en voz alta sus pensamientos pocas veces suelen funcionar, sin embargo parte de la fuerza de <i>Mira quién habla</i> yace en que Willis, como el esperma/feto/bebé, no siempre está hablando».​ Este mismo rol, lo repitió de nueva cuenta en la continuación <i>Mira quién habla también</i> (1990), la cual recaudó 47&nbsp;789&nbsp;074 dolares en Estados Unidos y,​ a diferencia de su predecesora, fue enlistada como una de las diez peores películas del actor.</p>
                    <p className="my-2">En 1987, Willis consiguió un éxito moderado al debutar como músico y grabar un álbum de pop-blues, con la discográfica Motown, titulado <i>The Return of Bruno</i>, el cual incluyó el sencillo «Respect Yourself», que llegó a convertirse en un <i>hit</i>,​ además de ser promovido por una parodia al estilo «<i>Spinal Tap</i>», donde se mostraban escenas de él mismo cantando en eventos famosos, tales como el festival de Woodstock.​ Aun cuando sus siguientes grabaciones no lograron ser tan exitosas ni populares, regresó a los estudios de grabación en repetidas ocasiones. El 3 de octubre de 1989 lanzó su segundo álbum musical tipo <i>blue eyed soul</i> denominado <i>If It Don't Kill You, It Just Makes You Stronger</i>, el cual fue grabado nuevamente con Motown y contiene un repertorio de diez temas musicales. De acuerdo al sitio web Allmusic: «En lugar de intentar agradarle a todos y crear proyectos de gran vanidad, Willis, uno de los muchos actores que decidieron probar la <i>music world</i>, ha decidido probar con la música que más le gusta y ha conseguido un buen resultado en este segundo lanzamiento. Willis no es un tenor de ópera, pero posee un grito tipo <i>blues</i> potente (sin tomar en consideración su talento con la armónica) que amerita su atronadora presencia en mezclas generalmente estruendosas».​ Desde entonces, se ha apartado de los escenarios musicales para aparecer, de vez en cuando, en las inauguraciones de algunos restaurantes Planet Hollywood, mismas en las que ha interpretado parte de su repertorio.</p>
                    <h4 className="mb-5 text-xl mt-3"><b>1990-2000</b></h4>
                    <p className="my-2">A inicios de la década de 1990, su carrera como actor sufrió un breve declive al aparecer en <i>flops</i>​ como <i>The Bonfire of the Vanities</i> (basada en el libro homónimo escrito por el estadounidense Tom Wolfe; recaudó casi 15,7 millones de dolares, de un presupuesto total de 47 millones de dolares),​ una película coescrita por él y titulada <i>El gran halcón</i> (cuya trama combina teorías de conspiración, sociedades secretas, misterios históricos y tecnología extravagante tipo postcyberpunk; recaudó 17.2 millones de dólares y tuvo un presupuesto de 65 millones de dólares),​ <i>Striking Distance</i> (donde interpretó a un policía de Pittsburgh; estrenada en 1993, recaudó 24,1 millones de dolares),​ <i>Mortal Thoughts</i> (donde participó al lado de Demi Moore, quien para entonces ya era su esposa) y <i>Billy Bathgate</i> (dirigida por Robert Benton), entre otras. En 1990, se lanzó la continuación de <i>Die Hard</i>, donde Willis volvió a interpretar el rol del oficial John McClane. La película tuvo una recepción variada por parte de la crítica; por ejemplo, el sitio web Time Out elogió la actuación de Willis al comentar en su reseña: «Nadie puede llevar el peso de una sola línea mejor que Willis. Además, él es inusual entre los hombres de acción de Hollywood, puesto que puede verse vulnerable al mismo tiempo que se ve invencible»,​ mientras que el crítico Jonathan Rosenbaum, de <i>Chicago Reader</i>, declaró de forma tajante en su evaluación: «Si tu idea de pasar un buen rato es viendo mucha estupidez y personas desagradables que insultan y tratan de forma brutal a otras, entonces esta película te gustará».​ <i>Die Hard 2</i> recaudó poco más de 240 millones de dolares en todo el mundo y contó con un presupuesto de 70 millones de dolares.​ Dos años después, el actor participó en la producción <i>Death Becomes Her</i>, dirigida por Robert Zemeckis, donde interpretó el papel de un cirujano plástico. A pesar de las críticas variadas, la película obtuvo buenas recaudaciones tras su estreno, al ganar más de 149 millones de dolares.</p>
                    <p className="my-2">Entre 1992 y 1994, Willis participó en comerciales televisivos del automóvil Subaru Legacy, diseñado por la japonesa Subaru,​ misma que determinó lanzar un número limitado de modelos bajo el mote «Subaru Legacy Touring Bruce», en honor al actor.​ En ese período obtuvo el rol estelar, junto con la inglesa Jane March, del <i>thriller</i> de carácter sexual <i>Color of Night</i> (1994) el cual, de acuerdo a la publicación <i>Entertainment Weekly</i>, a pesar de tener una mala recepción crítica tras su exhibición en cines, logró notabilidad al lanzarse en formato de video.​ Ese mismo año, consiguió un papel secundario en <i>Pulp Fiction</i>, <img className="max-h-full m-3 float-left" src="/images/willis_pulp_fiction.jpg" alt="Bruce willis en pulp fiction" title="Bruce willis pulp fiction" />película aclamada de Quentin Tarantino, con la que dio un nuevo estímulo a su trayectoria como actor, al interpretar el papel de Butch Coolidge. De acuerdo al periodista estadounidense Peter Bart: «al participar Willis en una película con presupuesto modesto, su salario iba a reducirse y, por lo tanto, también estaba en riesgo su estatus como actor, pero la estrategia... valió mucho la pena: <i>Pulp Fiction</i> no sólo le brindó un nuevo nivel de respeto a Willis como actor, sino que también le hizo ganar varios millones de dólares como resultado de su recaudación en taquilla».​ La apariencia y presencia física de Willis fueron aspectos cruciales para que Tarantino lo contratara: «Bruce tiene la apariencia de un actor de la década de 1950. No puedo pensar en ningún otro actor que posea ese <i>look</i>».​ Tras su estreno, recaudó casi 214 millones de dolares, cuando su presupuesto fue de tan solo ocho millones de dolares.​ Adicionalmente, en 1996 fungió como productor ejecutivo de la serie animada <i>Bruno the Kid</i>, en la que salía una representación suya en formato CGI. En un total de 37 episodios, dio voz a un niño de once años que se convierte en espía secreto de una organización llamada Globe.</p>
                    <p className="my-2">Posteriormente, asumió los papeles estelares de las cintas de ciencia ficción <i>Doce monos</i> (1995) y <i>El quinto elemento</i> (1997). En la primera, dirigida por Terry Gilliam e inspirada en la adaptación francesa <i>La Jetée</i> (1962), interpreta a James Cole, un convicto que vive en un futuro post-apocalíptico siniestro. Gilliam eligió a Willis porque consideraba que el actor evocaba la personalidad de Cole, como «alguien fuerte y peligroso, pero también vulnerable».​ Tras su estreno, recaudó casi 170 millones de dolares a nivel mundial;​ el especialista en cine Roger Ebert mencionó en su crítica: «La película es una celebración de la locura y la perdición, con un héroe que trata de prevalecer contra el caos de su condición, y es inadecuado. Esta es una fría, oscura y desanimada versión, e inclusive el romance entre Willis y Madeleine Stowe se siente desesperado, más allá de jubiloso. Todo está muy bien hecho y, cuanto más conoces sobre las películas (especialmente, en el aspecto técnico), más estás dispuesto a admirarlas. Y como entretenimiento, la cinta apela más a la mente que a los sentidos».​ Por otra parte, en <i>El quinto elemento</i>, dirigida por Luc Besson, Willis personifica a un taxista y exsoldado de las «fuerzas especiales»; previo a su estreno en cines, inauguró el festival de Cannes de 1997.​ Recaudó un total de 263 millones de dolares a nivel mundial, tres veces por encima de su presupuesto estimado en 80 millones de dolares. Cabe señalar que el 76% de las ganancias provino de fuera de Estados Unidos.</p>
                    <p className="my-2">A pesar de los anteriores éxitos de taquilla en los que estuvo involucrado, para finales de la década su carrera comenzó a caer en otro declive debido a que las siguientes películas en que participó fueron criticadas negativamente, como por ejemplo <i>The Jackal</i>, <i>Mercury Rising</i> y <i>Breakfast of Champions</i>. No obstante, <i>Armageddon</i>, dirigida por Michael Bay, se convirtió en la película más taquillera de 1998 a nivel mundial,​ a pesar de sus malas críticas. Un ejemplo de esto último es que Roger Ebert la haya enlistado como una de las películas más detestables que jamás haya visto y añadiese en su evaluación: «La película es un atentado a los ojos, los oídos, el cerebro, el sentido común y el deseo humano de un buen entretenimiento».​ También, ese año Willis prestó su voz e imagen en el videojuego <i>Apocalypse</i> para la consola PlayStation.​ En 1999, protagonizó la cinta de M. Night Shyamalan <i>The Sixth Sense</i>, donde interpretó el rol del psicólogo infantil Malcolm Crowe. La mencionada película obtuvo tanto una buena recaudación en taquillas como aclamación crítica,​ algo que ayudó de alguna forma a incrementar el interés en su carrera como actor. Entre 1999 y 2000, fungió como el portavoz de la compañía de gafas de sol Police y apareció en una serie de anuncios publicitarios impresos.</p>
                    <h4 className="mb-5 text-xl mt-3"><b>2000-2010</b></h4>
                    <p className="my-2">En 2000, Willis obtuvo un premio Emmy como «mejor actor invitado en una serie de comedia» por su participación en <i>Friends</i> (donde interpretó a uno de los novios de Rachel Green).​ Dicha actuación también le brindó una nominación en los premios American Comedy de 2001, en el rubro de «actor invitado más divertido en una serie de televisión», pero fue vencido por Christopher Walken y su aparición en <i>Saturday Night Live</i>, en 1975.​ Aunque en un inicio había sido elegido como Terry Benedict en <i>Ocean's Eleven</i> (2001), rechazó el papel con tal de trabajar en la composición de un nuevo álbum musical.​ Dicho compilatorio, <i>Bruce Willis - The Universal Masters Collection</i>, se lanzó el 3 de enero de 2000 y pertenece al género <i>blues rock</i>. Fue grabado con el sello discográfico Musicrama y contiene un total de 18 pistas, entre las cuales se incluyen dos versiones diferentes del <i>hit</i> «Respect Yourself». Más allá de un compilatorio original, <i>The Universal Masters</i> es una recopilación de los principales sencillos de sus dos anteriores producciones discográficas.​ A pesar de que esto le impidió participar en <i>Ocean's Eleven</i>, en la continuación de 2004 hace una aparición breve como él mismo. En 2007, apareció en la cinta <i>Planet Terror</i>, la primera de una doble presentación cinematográfica conocida como <i>Grindhouse</i>, donde interpreta al antagonista principal, el teniente Muldoon, el cual a su vez es un soldado mutante. Lo anterior marcó su segunda colaboración con el cineasta Robert Rodriguez, después de <i>Sin City</i>. Tras su estreno, <i>Planet Terror</i> recaudó 10,8 millones de dolares a nivel mundial.​ De acuerdo al crítico Kevin Maher, de <i>The Sunday Times</i>: «Es un fascinante legado al cine de horror y una imbécil compensación para una determinada generación de seguidores obsesionados con los senos, las armas y el derramamiento de sangre».​</p>
                    <p className="my-2">Willis asiste con frecuencia al programa televisivo <i>The Late Show with David Letterman</i>; desde su primera aparición, el 13 de septiembre de 1993, ha aparecido hasta en 21 emisiones distintas, mientras que su última intervención en el mismo ocurrió el 4 de octubre de 2010.​ En muchas de sus presentaciones realiza bromas elaboradas, como por ejemplo vestir en algún momento un traje naranja luminiscente en honor de la exhibición «<i>Las entradas</i>» en 2005,​ aparecer con la mitad de su rostro repleta de heridas simuladas de bala tras una balacera suscitada en 2006, cuando el entonces vicepresidente estadounidense Dick Cheney le disparó accidentalmente al abogado Harry Whittington mientras éstos participaban en una cacería de codornices en un rancho de Texas, y ocupar el lugar del presentador David Letterman, que se hallaba enfermo, en la emisión transmitida el 26 de febrero de 2003, aun cuando se anunció que Willis era un invitado más.​ En otro instante, Willis intentó romper un récord al permanecer bajo el agua, en una especie de parodia de David Blaine, por solamente dos segundos. El 12 de abril de 2007 apareció de nueva cuenta en el programa, esta vez vistiendo una peluca reminiscente a Sanjaya Malakar.​ Meses después, el 25 de junio, reapareció vistiendo un mini aerogenerador atado a la cabeza, como parte de una broma hecha en torno a su documental ficticio titulado <i>An Unappealing Hunch</i> («Una corazonada poco atractiva», en alusión a la producción <i>Una verdad incómoda</i>).​ A finales de 2008, apareció en un breve clip de video (proyectado en pleno programa de Letterman) donde realizaba una parodia de la cinta <i>High School Musical 3: Senior Year</i>,​ mientras que, el 8 de junio de 2009, realizó una nueva aparición en el programa al interpretar, en forma de parodia, a uno de los nuevos empleados del programa.​ El 1 de febrero de 2010, realizó un segmento cómico donde aseguraba haber «inventado» un par de «pantalones explosivos»; al final, sus propios pantalones acabaron con dos agujeros justo debajo de los bolsillos delanteros.​ En su más reciente aparición, en octubre de 2010, usó nuevamente una peluca, sólo que esta vez la misma estaba hecha de carne, para realizar una parodia del vestido, la bolsa y el sombrero hechos con filetes de carne cruda que Lady Gaga usó en la entrega de los premios MTV Video Music 2010.</p>
                    <p className="my-2">Cabe destacar también sus intervenciones en cuatro filmes al lado del también actor Samuel L. Jackson (<i>Loaded Weapon 1</i>, <i>Pulp Fiction</i>, <i>Die Hard with a Vengeance</i> y <i>El protegido</i>), con quien tenía programado trabajar asimismo en <i>Black Water Transit</i>, aunque al final esto no se pudo concretar. Willis trabajó igualmente con su hija mayor, Rumer Glenn, en el <i>thriller</i> <i>Hostage</i> (2005), donde interpretó a un exoficial de la unidad especial SWAT que es un negociador de rehenes, y la cual recaudó un total de 77,9 millones de dolares a nivel mundial.​ Joshua Tyler, del sitio web Cinema Blend, comentó en su análisis: «¿Necesitamos de nuevo al Bruce de la época de <i>Die Hard</i>? Mi respuesta visceral es no. Ya no es tan joven como alguna vez lo fue. En algún punto, como Silvester Stallone y Arnold Schwarzenegger, Willis va a tener que retirarse de esos roles de acción. También para entonces, tendrá demasiadas arrugas como para figurar como un héroe de acción creíble. De hecho, ya está cerca de eso».​ Cabe señalar que en dicha cinta, su hija Rumer le pidió a su padre que le diera un rol en la película, con tal de interpretar específicamente a la hija secuestrada del protagonista. Sin embargo, en una entrevista concedida al diario <i>Chicago Sun-Times</i>, este le dijo: «Cariño, no te voy a dar el papel así nada más, aun cuando soy uno de los productores de la película». Debido a ello, Rumer tuvo que hacer su propia audición y, al final, resultó elegida.​ Dos años después, en 2007, participó en el <i>thriller</i> <i>Seduciendo a un extraño</i>, al lado de Halle Berry, el cual recaudó poco más de 73 millones de dolares.​ Sin embargo, el filme obtuvo malas críticas;​ de acuerdo a la cadena <i>E!</i>: «Halle Berry y Bruce Willis tropiezan en este mal concebido <i>thriller</i> acerca de una periodista que investiga la muerte de una vieja amistad. Una contendiente segura para los premios de lo peor de este año».</p>
                    <p className="my-2">Ese mismo año, participó en el drama criminal <i>Alpha Dog</i>, junto a Sharon Stone (donde interpretó al padre de un joven narcotraficante; tuvo ganancias estimadas en 32,1 millones de dolares a nivel mundial, mientras que la crítica consideró que las actuaciones de Willis y Stone habían sido «exageradas»),​ así como en <i>Live Free or Die Hard</i>, donde volvió a interpretar a John McClane. En el programa de televisión <i>Ebert &amp; Roeper</i>, los críticos Richard Roeper y Katherine Tulich le dieron a la película una calificación regular; el primero mencionó al respecto: «No es la mejor entrega <i>Die Hard</i> ni la más emocionante, pero tiene mucha diversión», y señaló que era su continuación favorita de la original <i>Die Hard</i>, además de subrayar que Willis estaba «en el punto cumbre de su trayectoria como John McClane».​ La película recaudó un total de 383,5 millones de dolares a nivel mundial y contó con un presupuesto de 110 millones de dolares. También, apareció en las cintas <i>Algo pasa en Hollywood</i> (2008) y <i>Surrogates</i> (2009). La primera, coprotagonizada por Robert De Niro y Sean Penn, recaudó casi 6,7 millones de dolares,​ mientras que la restante obtuvo ganancias por más de 120 millones de dolares durante su exhibición en cines.​ En <i>Algo pasa en Hollywood</i>, De Niro interpreta a un productor de cine de Hollywood y Willis se interpreta a sí mismo. Tras su estreno, obtuvo críticas variadas; en el sitio Rotten Tomatoes obtuvo un 52% de críticas positivas.​ Respecto a la actuación de Willis en <i>Surrogates</i>, Peter Cowell, del periódico <i>Toronto Star</i>, mencionó: «La imagen del póster promocional de la película de un Willis en tono gris y canoso es una advertencia de que <i>Surrogates</i> no se trata de otra actuación psíquica del actor [...] Aquí tiene una doble misión, tanto como un humano como un robot, y de hecho suda y se acerca al borde de las lágrimas».</p>
                    <p className="my-2">Por otra parte, a pesar de que había sido convocado para interpretar al general estadounidense William R. Peers en la cinta <i>Pinkville</i>, un drama que iba a ser dirigido por Oliver Stone acerca de la investigación en torno a la matanza de Mỹ Lai (acontecida en 1968),​ este proyecto jamás logró concretarse debido a la huelga de guionistas en Hollywood de 2007-2008. En 2008, participó en el álbum <i>North Hollywood Shootout</i> de la banda de rock Blues Traveler, al brindar una interpretación <i>spoken word</i>​ en un arreglo instrumental de tipo blues-rock, mismo que terminó incorporado en el sencillo «Free Willis (Ruminations from Behind Uncle Bob's Machine Shop)». A principios de 2009, intervino nuevamente en otra campaña publicitaria que tenía como fin promover el cambio de nombre de la aseguradora Norwich Union a Aviva.​ En 2010 se estrenó la comedia <i>Cop Out</i>, la cual estelarizó junto a Tracy Morgan, dirigida por Kevin Smith, sobre dos policías que investigan el robo de una tarjeta de béisbol.​ Poco después, se le vio en el video musical de la canción «Stylo», de la banda Gorillaz.​ En marzo de 2010, dicho videoclip estableció un nuevo récord al ser visto 900&nbsp;000 veces en su día de estreno en el sitio YouTube, con lo que se convirtió en el video musical promocional más exitoso de YouTube.​ Ese mismo año, apareció brevemente en la película <i>The Expendables</i> junto con Sylvester Stallone y Arnold Schwarzenegger, trío propietario de la cadena de restaurantes Planet Hollywood, junto con otros actores de renombre. Dicha intervención fue la primera vez que los mencionados aparecieron juntos en una misma película; a pesar de ser una escena breve, era una de las más anticipadas de la producción. La misma se filmó a finales de 2009, en el interior de una iglesia.​ Luego, participó en <i>Red</i>, una adaptación de la miniserie de cómics homónima en la cual interpreta a Frank Moses y que se estrenó en Estados Unidos el 15 de octubre de 2010.</p>
                    <h4 className="mb-5 text-xl mt-3"><b>Posterior al 2010</b></h4>
                    <p className="my-2">Un proyecto que el actor tiene programado protagonizar es la adaptación cinematográfica del videojuego <i>Kane &amp; Lynch: Dead Men</i>.​ El 5 de mayo de 2010, se confirmó la producción de <i>Die Hard 5</i>, y Willis ha sido considerado para a interpretar una vez más al oficial John McClane.</p>
                    <p className="my-2">Para el 2012, Willis participó en la continuación de <i>The Expendables 2</i>.​ Anteriormente, Stallone había expresado su interés en que Willis retome su personaje en la secuela pero en un papel más importante; Willis confirmó su participación en la película el 6 de septiembre de 2011.​ La cinta fue la más taquillera de las tres, recaudando 311 millones de dólares.</p>

                    <div className=' w-full flex justify-end'>
                        <button className=' btn btn-circle w-36 my-5 text-2xl bg-gray-400' id='botonVisibilidad' onClick={handleVisible}>Leer más</button>
                    </div>



                    <div id='contenedorVisibilidad' className='oculto'>
                        <h2 className="mw-headline text-2xl py-10 text-center"><b>Vida privada</b></h2>
                        <h3 className="mb-5 text-xl mt-5"><b>Matrimonios y familia</b></h3>
                        <p className="my-2">Willis conoció a la actriz Demi Moore durante el estreno de la película <i>Procedimiento ilegal</i>; para entonces, Moore salía con el actor Emilio Estévez, quien participó en dicha cinta. Aun así, el 21 de noviembre de 1987, Willis se casó con Moore​ y tuvieron tres hijas: Rumer Willis (n. 16 de agosto de 1988), Scout LaRue Willis (n. 20 de julio de 1991) y Tallulah Belle Willis (n. 3 de febrero de 1994).</p>
                        <img className="max-h-full float-start m-3" src="/images/bruce_demmi.jpg" alt="Bruce willis y Demmi moore" title="Bruce willis y Demmi moore" />
                        <p className="my-2">La pareja se divorció el 18 de octubre de 2000, sin ofrecer alguna razón pública por su ruptura.Sobre ello, él mencionó: «Me sentí como si hubiera fallado como padre y como esposo al no ser capaz de hacer que esto funcionara». Incluso agradeció al actor Will Smith haberle ayudado a lidiar con dicha problemática. Tras su separación, se esparcieron rumores de que ambos volverían a casarse; sin embargo, Moore contrajo matrimonio con Ashton Kutcher, quince años menor que ella. Desde entonces, Willis ha mantenido una relación cercana tanto con Moore como con Kutcher, incluso asistiendo a su boda.​ En la actualidad, Moore y él comparten legalmente la custodia de sus hijas;​ Willis consideró a Kutcher como un miembro más de su «familia extendida».</p>
                        <p className="my-2">Una vez concretado el trámite de divorcio, Willis salió con las modelos María Bravo Rosado y Emily Sandberg;​ de igual forma, se comprometió con Brooke Burns, con quien terminó en 2004, tras meses de relación.</p>
                        <p className="my-2">El 21 de marzo de 2009 contrajo segundas nupcias con Emma Heming en las islas Turcas y Caicos, un evento al que asistieron sus tres hijas, Moore y Kutcher. Debido a que la ceremonia no fue legalmente vinculante, la pareja se casó de nuevo en una ceremonia civil llevada a cabo en Beverly Hills (California), tan solo seis días después de la boda en las islas ya mencionadas. En algunas declaraciones, Willis había expresado interés en tener más hijos. En 2012, anunció que su esposa dio a luz a una niña llamada Mabel Ray; esta sería su cuarta hija, ya que el actor tiene tres hijas de su matrimonio anterior, y la primera para la actriz. Para 2014, su esposa dio a luz a la segunda hija de ambos, llamada Evelyn Penn.</p>
                        <p className="my-2">A comienzos del 2022 la familia de Bruce, incluyendo su exesposa Demi Moore, anunciaron un comunicado señalando el retiro del actor debido a que fue diagnosticado con afasia, un trastorno del habla que puede ser causado por un ACV (ataque cerebrovascular) o un traumatismo, entre otros. Sin embargo, en febrero de 2023 informaron que su condición había progresado y que disponían de un diagnóstico más específico: demencia frontotemporal.</p>
                        <p className="my-2">En marzo de 2023, Willis y su esposa Emma Heming renovaron sus votos matrimoniales.</p>
                        <h3 className="mb-5 text-xl mt-5"><b>Religión</b></h3>
                        <p className="my-2">En algún momento, el actor fue luterano (perteneció específicamente a la Iglesia luterana Sínodo de Misuri),​ aunque dejó de practicar dicha religión después de declarar lo siguiente en una entrevista realizada para la revista estadounidense <i>George</i>, en julio de 1998:</p>
                        <blockquote className="flexquote">
                            <div className="flex">
                                <div className="quote">Las religiones organizadas son, en mi opinión general, vertientes moribundas [...] Todas eran más importantes cuando no sabíamos por qué se movía el Sol, por qué cambiaba el clima, por qué ocurrían los huracanes o qué generaba los volcanes [...] La religión contemporánea es el sendero final de la mitología moderna. Aunque hay gente que interpreta la Biblia literalmente. ¡Literalmente! Elijo no creer de esa manera. Y eso es lo que hace a Estados Unidos tan interesante, ¿te das cuenta?</div>
                            </div>
                            <div className="cite">Bruce Willis​</div>
                        </blockquote>
                        <h3 className="mb-5 text-xl mt-5"><b>Intereses empresariales</b></h3>
                        <p className="my-2">Willis es arrendatario de un apartamento en la Torre Trump (en la ciudad de Nueva York),​ y otro en el complejo departamental Riverside South (conocido también como Trump Place),​ además de propietario de un local en Los Ángeles, una casa en Malibú (California), un rancho en Montana, una casa playera en Parrot Cay (una pequeña isla radicada en el conjunto Turcas y Caicos) y numerosas propiedades en el centro turístico invernal Sun Valley (Idaho).​ En 1997, Willis cofundó la compañía teatral Company of Fools, una empresa sin ánimos de lucro radicada en Idaho.</p>
                        <p className="my-2">De igual forma, posee su propia compañía productora de filmes denominada Cheyenne Enterprises, fundada en 2000 junto a su socio Arnold Rifkin.​ De manera similar cofundó, en Los Ángeles, la productora Willis Brothers Films con su hermano David Willis y el empresario Stephen Eads.​ Es dueño de varios negocios pequeños en Hailey, Idaho, incluyendo The Mint Bar y The Liberty Theater, siendo cofundador de Planet Hollywood junto con los actores Arnold Schwarzenegger y Sylvester Stallone.​ En 2009 firmó un contrato para convertirse en el rostro internacional del vodka Sobieski, de la empresa Belvedere SA, a cambio de un 3,3% de sus acciones.</p>
                        <h3 className="mb-5 text-xl mt-5"><b>Otros intereses</b></h3>
                        <p className="my-2">Siendo un fanático del equipo de baloncesto New Jersey Nets, Willis realizó una serie de comentarios polémicos el 29 de abril de 2007, durante un juego de eliminación directa (<i>playoff game</i>) de los Nets que fue transmitido por el canal de cable canadiense TSN, al repetir una frase característica de <i>Die Hard</i>: «Yippee-Ki-Yay, hijo de puta», hacia el final de la entrevista que le hicieron.​ Tras reaccionar tiempo después, se excusó culpando a la descompensación horaria y diciendo: «A veces, sobrestimo mi capacidad para estar activo bajo presión durmiendo lo insuficiente».</p>
                        <p className="my-2">El 5 de mayo de ese mismo año, alguien utilizó el alias «Walter_B» para responder preguntas de manera detallada en el sitio web Ain't it Cool News, donde los cibernautas se hallaban discutiendo el hecho de que <i>Live Free or Die Hard</i> recibiera una clasificación PG-13, en vez de una R (al igual que ocurriera con las tres anteriores cintas de la franquicia <i>Die Hard</i>).​ Entre dichas respuestas se encontraba información exclusiva sobre la película aún sin estrenar, la temática de la serie, críticas directas hacia los miembros del reparto de otras películas y varias sentencias triviales sobre el cine. Al principio, varios se mostraron escépticos a la idea de que «Walter_B» fuera Willis, sin embargo, el 9 de mayo, el actor reveló su identidad en una sesión de videollamada (utilizando para ello iChat).</p>
                        <h3 className="mb-5 text-xl mt-5"><b>Ideología política</b></h3>
                        <p className="my-2">En 1988, Moore y Willis realizaron una campaña a favor de la candidatura presidencial del entonces gobernador de Massachusetts Michael Dukakis. Cuatro años después, en 1992, apoyó la reelección del presidente George H. W. Bush, figurando también como crítico de Bill Clinton. No obstante, en 1996 declinó respaldar al oponente de Clinton, el republicano Bob Dole, debido a que este último criticó la interpretación de Moore en la cinta <i>Striptease</i>.​ Asimismo, fue un orador invitado a la Convención Nacional Republicana de 2000,​ apoyando de manera activa a George W. Bush más tarde. A pesar de ello, el actor no realizó contribución alguna durante la campaña presidencial de 2008; en varias entrevistas concedidas en junio del año anterior, declaró que todavía mantenía algunas ideologías del partido republicano.</p>
                        <p className="my-2">En 2006 propuso que Estados Unidos debía invadir Colombia, con tal de poner fin al narcotráfico.​ Willis ha dicho en múltiples entrevistas que apoya la iniciativa de ofrecer mejores salarios a los maestros y policías, aunque a la vez desaprueba la tutela y tratos de su país para con los nativos americanos.​ Igualmente declaró que es un gran simpatizante del derecho a poseer armas:</p>
                        <blockquote className="flexquote">
                            <div className="flex">
                                <div className="quote">«Todos tienen derecho a usar armas [en territorio estadounidense, de acuerdo a la Segunda Enmienda a la Constitución de los Estados Unidos].​ Si le quitas las armas a sus propietarios que, legalmente, pueden utilizarlas, entonces los únicos que podrán tenerlas serán los criminales [...] Incluso un pacifista se pondría violento si alguien intentara matarlo. [... Definitivamente] lucharías por tu vida».​</div>
                            </div>
                        </blockquote>
                        <p className="my-2">Willis ha criticado a la derecha cristiana y su influencia en el Partido Republicano. En febrero de 2006 apareció en Manhattan para hablar sobre el filme <i>16 Blocks</i> con los medios de comunicación. Uno de los reporteros intentó preguntarle su opinión sobre los eventos actuales, pero fue interrumpido por Willis a la mitad de su cuestionamiento: </p>
                        <blockquote className="flexquote">
                            <div className="flex">
                                <div className="quote">«Estoy harto de responder esta maldita pregunta. Soy republicano sólo porque quiero un gobierno más pequeño, es decir menos intromisión gubernamental. Quiero que dejen de cagar en mi dinero y en su dinero y los impuestos que le damos de un 50% de... cada año. Quiero que se hagan fiscalmente responsables y que esos malditos grupos de presión estén fuera de Washington. Hagan eso y diré que soy republicano... Odio el gobierno, ¿OK? Soy un apolítico. Anota eso. No soy republicano».​</div>
                            </div>
                        </blockquote>
                        <p className="my-2">El nombre de Willis fue incorporado en un anuncio publicado en <i>Los Angeles Times</i> el 17 de agosto de ese mismo año, en el que condenaba a Hamás y Hezbolá y apoyaba a Israel en la Guerra del Líbano de 2006.</p>
                        <h3 className="mb-5 text-xl mt-5"><b>Intereses militares</b></h3>
                        <p className="my-2">A lo largo de su carrera cinematográfica, Willis ha interpretado a varios personajes militares en filmes como <i>The Siege</i>, <i>Hart's War</i>, <i>Lágrimas del sol</i> y <i>Grindhouse</i>. Criado en el seno de una familia militar, el también productor ha sido visto vendiendo galletas de jóvenes escultistas para los miembros de las fuerzas armadas estadounidenses. En 2002, su hija menor, Tallulah, sugirió que este comprara galletas a chicas escultistas para enviarlas a las tropas. Ante esto, Willis adquirió un total de 12&nbsp;000 cajas de galletas, las cuales se distribuyeron luego a los marinos a bordo del USS <i>John F. Kennedy</i>, así como a otras tropas que se hallaban, a su vez, estacionadas en Medio Oriente.​ Al año siguiente, visitó Irak como parte de un recorrido de la organización USO, donde cantó para las tropas, acompañado de su banda The Accelerators.​ Incluso, consideró en algún momento unirse a la milicia para combatir en la segunda guerra de Irak, sin embargo fue disuadido por su edad (48 años, en ese entonces).​ Por otra parte, se creía que había ofrecido un total de un millón de dólares a cualquier no combatiente que brindara información útil sobre los líderes terroristas Osama bin Laden, Ayman al-Zawahiri o Abu Musab al-Zarqawi. No obstante, en junio de 2007, en la edición respectiva de la revista <i>Vanity Fair</i>, aclaró que había hecho dicha declaración de manera hipotética y, en ningún caso, debía tomarse de manera literal. Asimismo, criticó a los medios por su cobertura en torno a la guerra, considerando que la prensa se enfocó más en los aspectos negativos del conflicto:</p>
                        <blockquote className="flexquote">
                            <div className="flex">
                                <div className="quote">Fui a Iraq al ver que quienes estaban ahí eran soldados —jóvenes en su mayoría— ayudando a otra gente; los ayudaban a recuperar de nuevo el poder, a abrir hospitales, a conseguir agua nuevamente y no escuchas nada de eso en las noticias. Solamente te informan de 'X número de personas fueron asesinadas hoy', lo cual creo que es un deservicio enorme. Es como escupirles a todos esos jóvenes que están allá combatiendo para ayudar a este país.​</div>
                            </div>
                        </blockquote>
                        <p className="my-2">En el año 2005, Willis mencionó que quería «hacer una cinta en pro de la guerra, donde los soldados estadounidenses aparecieran como combatientes osados que buscan la libertad y la democracia».​ Dicho proyecto habría de relatar las experiencias de los miembros del 24° Regimiento de Infantería, quienes pasaron un tiempo considerable en Mosul, siendo elogiados por ello a su arribo a Estados Unidos. Además, se inspiraría en los escritos del bloguero Michael Yon, un exsoldado de las Boinas Verdes, que había recibido el encargo como corresponsal encargado de informar sobre las actividades del Regimiento. Willis describió que la historia del filme trataría sobre «esos sujetos que son obligados a hacer lo que hacen por muy poco dinero para defender y luchar por lo que consideran que es la libertad».​ Sin embargo, a partir de entonces, no se ha hecho anuncio alguno en torno a dicha producción.</p>
                        <h2 className="mw-headline text-2xl py-10 text-center"><b>Referencias culturales</b></h2>
                        <p className="my-2">En 1996, Roger Director, uno de los guionistas y productores de <i>Luz de luna</i>, redactó un <i>roman à clef</i> (es decir, una novela que describe la vida de alguien a partir de la combinación de hechos reales y sucesos ficticios) sobre el actor, titulada <i>A Place to Fall</i>.​ Más tarde, en su autobiografía publicada en 2000, denominada <i>Cybill Disobedience</i>, Cybill Shepherd comentó que Willis estaba enojado con Director, puesto que su personaje había sido descrito como un «actor neurótico y petulante».</p>
                        <p className="my-2">Dos años después, en 1998, Willis participó en el videojuego <i>Apocalypse</i>, para la consola PlayStation; al principio, se decía que él aparecería como un personaje secundario y no como el protagonista. Sin embargo, la empresa encargada de su producción volvió a rediseñar el juego, esta vez utilizando la apariencia física y voz de Willis, cambiando completamente el diseño original, para que el actor fungiera como el personaje estelar de la trama.</p>
                        <p className="my-2">En casi todas las interpretaciones de Bruce Willis le dobla al español de España el actor Ramón Langa.</p>

                    </div>

                </main>
            </LayoutRoot>
        </>
    );
}
